// <auto-generated />
namespace BH_CalendarMaker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class 널필드업데이트 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(널필드업데이트));
        
        string IMigrationMetadata.Id
        {
            get { return "202011250516036_널필드업데이트"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
