// <auto-generated />
namespace BH_CalendarMaker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class 컬러코드추가 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(컬러코드추가));
        
        string IMigrationMetadata.Id
        {
            get { return "202111100656216_컬러코드추가"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
